Pull request
OriMelamed/invoice-app pull request #1
Opened 2021-10-06 17:29 UTC by OriMelamed

2021-10-06 17:43 UTC, dpaluy requested changes

2021-10-06 17:43 UTC, dpaluy commented on Gemfile
> +gem 'will_paginate', '~> 3.3'
@OriMelamed This gem is very inefficient and we should use https://github.com/ddnexus/pagy instead

2021-10-06 17:43 UTC, dpaluy commented on app/controllers/buyers_controller.rb
> +end
END of line is missing, please use Visual Studio plugin to automate this

2021-10-06 17:45 UTC, dpaluy requested changes

2021-10-06 17:45 UTC, dpaluy commented on config/routes.rb
> +  resources :buyers do
This looks good. I recommend checking `:shallow`

2021-10-07 12:44 UTC, OriMelamed commented on Gemfile
> +gem 'will_paginate', '~> 3.3'
change to pagy for the pagination

2021-10-07 13:16 UTC, merged